services:
  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg14
    environment:
      POSTGRES_USER: ${DB_USER:-marketuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-marketpass}
      POSTGRES_DB: ${DB_NAME:-marketdb}
    ports:
      - "9020:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@market.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "9021:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - timescaledb

volumes:
  pgadmin:
    driver: local
  postgres:
    driver: local