services:
  backtest-interface:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - backtest-interface:latest
    image: backtest-interface:latest
    ports:
      - "9018:8501"
    volumes:
      - ./:/app
    container_name: backtest-interface
    environment:
      - BOT_REPO_PATH=/app
      - DATABASE_PATH=/app/database
      - BACKTEST_INTERFACE_REPO_PATH=/app/backtest_interface/streamlit
    restart: always
