# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json

name: Check Changes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      cpp-changed: ${{ steps.changes.outputs.cpp }}
      cmake-changed: ${{ steps.changes.outputs.cmake }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            cpp:
              - 'cpp_**/**'
              - 'ChartDirector/**'
              - '*.cpp'
              - '*.h'
              - '*.hpp'
            cmake:
              - '**/CMakeLists.txt'
              - 'CMakeLists.txt'
              - 'build_and_run.sh'